# Generated by Django 4.0 on 2022-01-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_link',
            field=models.CharField(default='', max_length=150, verbose_name='Link to the cover'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Old ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=100, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='Pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=None, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
