# Generated by Django 4.0 on 2022-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_book_cover_link_book_isbn_book_isbn_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Link to the cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='ISBN 10'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
